services:
  client:
    build:
        context: .
        target: client
    networks:
      - server
      - default
    env_file:
      - .env
networks:
    server:
        name: tomo-server-network
        external: true
